[package]
name = "slint_sample"
version = "0.2.3"
build = "build.rs"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.9.1"

[build-dependencies]
slint-build = "1.9.1"
