[package]
name = "actix_web_sample2_cookie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.1"
actix-session = {version = "0.8.0", features = ["cookie-session"]}
actix-http = "3.5.1"
tera = "1.19.1"
mime = "0.3.17"
env_logger = "0.10.1"
log = "0.4.20"
anyhow = "1.0.77"
dotenv = "0.15.0"
serde = {version = "1.0.193", features = ["derive"]}
sea-orm = { version = "0.12.10" , features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"], default-features = false }
http = "1.0.0"
thiserror = "1.0.53"
validator = "0.16.1"
