[package]
name = "this_error"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.17"
thiserror = { version = "1.0.50", features = [] }
anyhow = "1.0.75"
