[package]
name = "mongodb_sample"
version = "0.2.0"
edition = "2021"
rust-version = "1.82.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "3.1.0"
tokio = {version = "1.40.0", features = ["full"]}
serde = {version = "1.0.210", features = ["derive"]}
proc-macro2 = "1.0.88"
futures-util = "0.3.31"
anyhow = "1.0.90"
lombok = "0.4.0"
async-trait = "0.1.83"
time = "0.3.36"