[package]
name = "test1"
version = "0.1.0"
authors = ["taishow2019 <taishow2007@live.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
