[package]
name = "my_bevy_game"
version = "0.2.4"
edition = "2021"
rust-version = "1.75"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
image = "0.24.7"
winit = "0.28.7"
