[package]
name = "my_bevy_game"
version = "0.2.1"
edition = "2021"
rust-version = "1.73"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
image = "0.24.6"
winit = "0.28.6"
