[package]
name = "my_bevy_game"
version = "0.3.0"
edition = "2021"
rust-version = "1.82"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.15.0"
image = "0.25.5"
winit = "0.30.5"
