// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCvmQZYelEXMESVUzksDscI7WqCJmkMrg',
    appId: '1:163776987535:web:247ee777d46a3683834bfa',
    messagingSenderId: '163776987535',
    projectId: 'taishow2006-firebase-overview',
    authDomain: 'taishow2006-firebase-overview.firebaseapp.com',
    storageBucket: 'taishow2006-firebase-overview.appspot.com',
    measurementId: 'G-SZQ5SDZW90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKZaIYEXVVh3pyyBL23f3_LYhEuT1oBSQ',
    appId: '1:163776987535:android:e5a40cd5e0ef834f834bfa',
    messagingSenderId: '163776987535',
    projectId: 'taishow2006-firebase-overview',
    storageBucket: 'taishow2006-firebase-overview.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHYW-97kAvEEgH3FMPWa2OYu_MRkVyYD4',
    appId: '1:163776987535:ios:e9fcd995ba244c3f834bfa',
    messagingSenderId: '163776987535',
    projectId: 'taishow2006-firebase-overview',
    storageBucket: 'taishow2006-firebase-overview.appspot.com',
    iosClientId: '163776987535-td6bd4gnfveneqg415qoqvsc1rfe7kbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.crashlytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHYW-97kAvEEgH3FMPWa2OYu_MRkVyYD4',
    appId: '1:163776987535:ios:b309da55cad50892834bfa',
    messagingSenderId: '163776987535',
    projectId: 'taishow2006-firebase-overview',
    storageBucket: 'taishow2006-firebase-overview.appspot.com',
    iosClientId: '163776987535-0vh2ms21hos9ve128m4c02foencl0cpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.crashlytics.RunnerTests',
  );
}
