// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaECeIytGa2inG5tpRHwGo4uRuEuoAkOg',
    appId: '1:162013296430:web:0ccfc0d98788884d47acbf',
    messagingSenderId: '162013296430',
    projectId: 'taishow-firebase-overview2023',
    authDomain: 'taishow-firebase-overview2023.firebaseapp.com',
    storageBucket: 'taishow-firebase-overview2023.appspot.com',
    measurementId: 'G-09MSBM3FGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_3TD50piPbyZZMdM0eiQeJzbsl1ivCPY',
    appId: '1:162013296430:android:9dadb5194a978bcd47acbf',
    messagingSenderId: '162013296430',
    projectId: 'taishow-firebase-overview2023',
    storageBucket: 'taishow-firebase-overview2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAVZL76OCtlhZERy0FrKqMgpONQeTGYs4',
    appId: '1:162013296430:ios:0c80b32d1bd347ec47acbf',
    messagingSenderId: '162013296430',
    projectId: 'taishow-firebase-overview2023',
    storageBucket: 'taishow-firebase-overview2023.appspot.com',
    iosBundleId: 'com.example.firebaseOverview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAVZL76OCtlhZERy0FrKqMgpONQeTGYs4',
    appId: '1:162013296430:ios:dd89d54cd8b9659d47acbf',
    messagingSenderId: '162013296430',
    projectId: 'taishow-firebase-overview2023',
    storageBucket: 'taishow-firebase-overview2023.appspot.com',
    iosBundleId: 'com.example.firebaseOverview.RunnerTests',
  );
}
