// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzeTwLmZpVcUUghFJyBKYE7p7y4--2XCo',
    appId: '1:929188211333:web:49ed1177b9886b321ed7ec',
    messagingSenderId: '929188211333',
    projectId: 'taishow-firebase-overview',
    authDomain: 'taishow-firebase-overview.firebaseapp.com',
    storageBucket: 'taishow-firebase-overview.appspot.com',
    measurementId: 'G-3P80D2BN4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrTQXbvGOBU9k6X33GsuB0OBHi65WJtGI',
    appId: '1:929188211333:android:66dad384807ffe4f1ed7ec',
    messagingSenderId: '929188211333',
    projectId: 'taishow-firebase-overview',
    storageBucket: 'taishow-firebase-overview.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjgKBCQPeY2CqyfiWszv0MAYK-ebmGwQI',
    appId: '1:929188211333:ios:5752448234e13d361ed7ec',
    messagingSenderId: '929188211333',
    projectId: 'taishow-firebase-overview',
    storageBucket: 'taishow-firebase-overview.appspot.com',
    iosBundleId: 'com.example.firebaseOverview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjgKBCQPeY2CqyfiWszv0MAYK-ebmGwQI',
    appId: '1:929188211333:ios:4697531172b1a4711ed7ec',
    messagingSenderId: '929188211333',
    projectId: 'taishow-firebase-overview',
    storageBucket: 'taishow-firebase-overview.appspot.com',
    iosBundleId: 'com.example.firebaseOverview.RunnerTests',
  );
}
