name: Consistent Pull Request

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  consistent-pull-request:
    name: Consistent Pull Request
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write
    steps:
      - name: Check pr label name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          rules: |
            main <- feature/* [feature]

      - name: Check head branch name
        with:
          rules: |
            feature/* dependabot/*

      - name: Check base branch name
        with:
          rules: |
            main <- feature/* dependabot/* 
