name: Consistent Pull Request

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  consistent-pull-request:
    name: Consistent Pull Request
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write
    steps:
      - name: Check pr label name
        uses: praha-inc/action-restrict-pr-label@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          rules: |
            main <- feature/* [Feature]
            main <- feature/update* [Update]

      - name: Check head branch name
        uses: praha-inc/action-restrict-head-branch@v1.0.2
        with:
          rules: |
            feature/* dependabot/* update/*

      - name: Check base branch name
        uses: praha-inc/action-restrict-base-branch@v1.0.2
        with:
          rules: |
            main <- feature/* dependabot/* update/*
